### ISSUE TITLE
No "host/ble_hs.h" file

### ISSUE THREAD

**Issue by hmcashan13** [apache/mynewt-documentation#52]
This is the error message I'm getting:
****
Compiling apps/ble_app/src/main.c
Error: apps/ble_app/src/main.c:4:25: fatal error: host/ble_hs.h: No such file or directory
 #include "host/ble_hs.h"
****
I used the exact source code that is offered and I was able to run the bare bones application with no problem. I'm working with a nrf52 Adafruit feather with boot loader pre-soldered with myNewt pre-bootloaded and a J-Link Segger mini.

**Comment by andrzej-kaczmarek** [comment]
you need to include NimBLE host packages in your app, e.g. `@apache-mynewt-nimble/nimble/host`
you will also need at least HCI transport package: `@apache-mynewt-nimble/nimble/transport`
